{"name": "Demo failed test cases", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Python-Selenium\\Python_SeleniumBDD\\Python_Selenium\\venv1\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Python-Selenium\\Python_SeleniumBDD\\Python_Selenium\\venv1\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\testing\\steps\\login_feature.py\", line 40, in step_impl\n    assert False\n           ^^^^^\n"}, "steps": [{"name": "Given : Navigate to Home page", "status": "passed", "start": 1727287106380, "stop": 1727287107428}, {"name": "Then Fail the test case", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Python-Selenium\\Python_SeleniumBDD\\Python_Selenium\\venv1\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Python-Selenium\\Python_SeleniumBDD\\Python_Selenium\\venv1\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\testing\\steps\\login_feature.py\", line 40, in step_impl\n    assert False\n           ^^^^^\n"}, "start": 1727287107428, "stop": 1727287107431}], "attachments": [{"name": "failure_screenshot", "source": "5e23740d-e2ab-4b36-a903-4fe13adda1e5-attachment.png", "type": "image/png"}], "start": 1727287106380, "stop": 1727287107670, "uuid": "b423c7f9-fe19-4154-af46-cf150781bc7c", "historyId": "ce7f5c9b51f1a8e229623049aeb7cdce", "fullName": "Search Functionality: Demo failed test cases", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Search Functionality"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}